### ISSUE TITLE
Operator Map Types (Metamethods)

### ISSUE THREAD

**Issue by TIMONz1535** [lolleko/gmod-typescript#7]
Hi, I found this project and decided to try it out. You've done a great job! The GLua API works very well. And it's really cool that anyone can try out a working toolkit, not a theoretical one (I've tried CSharp.lua, but there's no complete GLua API for it anywhere).

I am faced with the problem that **Vector**, **Angle** and **VMatrix** have metamethods for operator overloading, but they cannot work in **TypeScript**. This is by design of the **TypeScript**, because the **JavaScript** does not have an operator overloading :<

However, I found that the developers of the **TypeScriptToLua** provided special mapping functions:
https://typescripttolua.github.io/docs/advanced/language-extensions#operator-map-types

Also **Vector** and **Angle** have index variables (x, y, z, p, y, r, pitch, yaw, roll) that can be declared in the interface, instead of doing them through mapping functions.

For example operators as methods:
```ts
interface Vector {

	x: number, 1: number;
	y: number, 2: number;
	z: number, 3: number;

	add: LuaAdditionMethod<Vector, Vector>;
	sub: LuaSubtractionMethod<Vector, Vector>;
	// mul: LuaMultiplicationMethod <Vector, Vector> & LuaMultiplicationMethod <number, Vector>; // two methods (+1 overload)
	mul: LuaMultiplicationMethod <Vector | number, Vector>; // its also correct but one method
	div: LuaDivisionMethod <number, Vector>;
	neg: LuaNegationMethod <Vector>; // or 'negate' or 'unm'?

	...
```

how it looks
```ts
		let offset = Vector(0, 0, 10)
		let basePoint = Vector(0, 0, 1000)
		instance.pos = Vector()
		instance.pos[3] = 30
		instance.pos.z = 30
		instance.pos.y = instance.pos.y + 20
		instance.pos = instance.pos.add(basePoint)

		instance.pos = instance.pos.mul(Vector(0, 0, 1000))
		instance.pos = instance.pos.mul(2)
		instance.pos = instance.pos.div(2)

		instance.pos = instance.pos.neg().mul(2).add(basePoint).sub(offset)
```

and gets this lua code
```lua
        local offset = Vector(0, 0, 10)
        local basePoint = Vector(0, 0, 1000)
        instance.pos = Vector()
        instance.pos[3] = 30
        instance.pos.z = 30
        instance.pos.y = instance.pos.y + 20
        instance.pos = instance.pos + basePoint
        instance.pos = instance.pos * Vector(0, 0, 1000)
        instance.pos = instance.pos * 2
        instance.pos = instance.pos / 2
        instance.pos = ((-instance.pos * 2) + basePoint) - offset
```

Could you add operators and index variables to your declarations?

**Comment by lolleko** [comment]
I haven't had time to add the new operator mappings since we added them to TSTL, but I can't believe I forgot the component accessors for vector, angle... 😅 

I added a new modifier that allows adding fields to interfaces manually in https://github.com/lolleko/gmod-typescript/commit/565d0c75c7714717728813446bec6a8c1c3b3d09#diff-911b077f0ba1d3ab0115fbec7b36e54aaf521f6cce0dcd6dfd790b5bad005c27.

So far, I only added missing fields to Vector because I am a bit limited on time.
I really would appreciate a PR that adds angle, vmatrix.... to `modification_db.json`. Otherwise, you have to wait a bit longer until have time to add them myself.

I will do a npm release once all the relevant ops mappings are in.
